### PR TITLE
examples: update debian

### PR DESCRIPTION
**Pull request by AkihiroSuda**

### CODE REVIEW

**Comment by AkihiroSuda** [comment]
Arch linux failure

```
+ limactl shell archlinux sudo cat /var/log/cloud-init-output.log
Cloud-init v. 21.2 running 'init-local' at Mon, 02 Aug 2021 06:26:11 +0000. Up 16.68 seconds.
2021-08-02 06:26:12,983 - util.py[WARNING]: failed stage init-local
failed run of stage init-local
------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/cloudinit/cmd/main.py", line 652, in status_wrapper
    ret = functor(name, args)
  File "/usr/lib/python3.9/site-packages/cloudinit/cmd/main.py", line 361, in main_init
    init.apply_network_config(bring_up=bool(mode != sources.DSMODE_LOCAL))
  File "/usr/lib/python3.9/site-packages/cloudinit/stages.py", line 744, in apply_network_config
    return self.distro.apply_network_config(netcfg, bring_up=bring_up)
  File "/usr/lib/python3.9/site-packages/cloudinit/distros/__init__.py", line 210, in apply_network_config
    dev_names = self._write_network_config(netconfig)
  File "/usr/lib/python3.9/site-packages/cloudinit/distros/arch.py", line 67, in _write_network_config
    return self._supported_write_network_config(netconfig)
  File "/usr/lib/python3.9/site-packages/cloudinit/distros/__init__.py", line 122, in _supported_write_network_config
    renderer.render_network_config(network_config)
  File "/usr/lib/python3.9/site-packages/cloudinit/net/renderer.py", line 54, in render_network_config
    return self.render_network_state(
  File "/usr/lib/python3.9/site-packages/cloudinit/net/netplan.py", line 237, in render_network_state
    self._net_setup_link(run=self._postcmds)
  File "/usr/lib/python3.9/site-packages/cloudinit/net/netplan.py", line 257, in _net_setup_link
    subp.subp(cmd, capture=True)
  File "/usr/lib/python3.9/site-packages/cloudinit/subp.py", line 293, in subp
    raise ProcessExecutionError(stdout=out, stderr=err,
cloudinit.subp.ProcessExecutionError: Unexpected error while running command.
Command: ['udevadm', 'test-builtin', 'net_setup_link', '/sys/class/net/lo']
Exit code: 1
Reason: -
Stdout: 
Stderr: Trying to open "/etc/systemd/hwdb/hwdb.bin"...
        Trying to open "/etc/udev/hwdb.bin"...
        Trying to open "/usr/lib/systemd/hwdb/hwdb.bin"...
        Trying to open "/usr/lib/udev/hwdb.bin"...
        === trie on-disk ===
        tool version:          249
        file size:        11124547 bytes
        header size             80 bytes
        strings            2374771 bytes
        nodes              8749696 bytes
        Load module index
        Found cgroup2 on /sys/fs/cgroup/, full unified hierarchy
        Found container virtualization none.
        Network interface NamePolicy= disabled on kernel command line, ignoring.
        Loaded timestamp for '/etc/systemd/network'.
        Loaded timestamp for '/run/systemd/network'.
        Parsed configuration file /usr/lib/systemd/network/99-default.link
        Parsed configuration file /run/systemd/network/10-netplan-eth0.link
        Created link configuration context.
        lo: Failed to query device driver: Operation not supported
        lo: No matching link configuration found.
        Builtin command 'net_setup_link' fails: No such file or directory
        Unload module index
        Unloaded link configuration context.
------------------------------------------------------------
```

https://cirrus-ci.com/task/5593459898712064?logs=test#L307

cc @jandubois

**Comment by AkihiroSuda** [comment]
Seems https://github.com/systemd/systemd/issues/20300 , regression in systemd v249 https://github.com/systemd/systemd/commit/70f32a260b5ebb68c19ecadf5d69b3844896ba55

**Comment by jandubois** [comment]
> https://mirror.pkgbuild.com/images/v20210801.30574/Arch-Linux-x86_64-cloudimg-20210801.30574.qcow2 is affected because it uses systemd 249 (249.2-1-arch).

What do you want to do about it? Revert the update to the ArchLinux example until the issue is fixed upstream?

Or maybe not create `network-config` if the only entry is `eth0`?  Or add a limayaml setting for it?

**Comment by AkihiroSuda** [comment]
Reverted arch.

**Pull request merged**
